# -*- coding: utf-8 -*-
"""200901075_Assign_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZIbld-cVEWlt7JSgU8ycmpmxoHuZWRHX
"""

#Modul 1

import re
#taking expression from user
expression = input("Please enter expression: ")    #taking expression from user

#building regex
regex = r"(\d+)|([a-zA-Z]+)|(\+)|(-)|(\*)|(/)|(\()|(\))"
#tokenizing the expression
tokens = []                    
for match in re.finditer(regex, expression):   
    token = match.group(0)   #taking the matched token
    tokens.append(token)
print("Tokens: ")
print(tokens)  #prints output

#Module 2

import ast
#taking expression from user
expression = input("Please enter expression: ")  #taking expression from user

#parsing expression into tree
tree = ast.parse(expression)

#print output
for node in ast.walk(tree):
    print(type(node).__name__)